### ISSUE TITLE
Alacritty Theme installation

### ISSUE THREAD

**Issue by mngshm** [Everblush/terminal-emulators#11]
@prateektade Could you recheck the alacritty theme installation procedure. I am not able to enable the theme after using `import` method. 
Error: 
```Invalid Import type: expected a sequence```

**Comment by mngshm** [comment]
I think we should prolly move back to the manual installation procedure. I don't find any fix for it.

**Comment by prateektade** [comment]
> I think we should prolly move back to the manual installation procedure. I don't find any fix for it.

Yes I think that seems to be a problem with all color schemes so could be related to upstream somehow. Copying the colors to `alacritty.yml` file works fine.

**Comment by mngshm** [comment]
yes... So i'll commit back to manual procedure
