### ISSUE TITLE
Suggestions for potential changes to the repository

### ISSUE THREAD

**Issue by prateektade** [Everblush/terminal-emulators#8]
Hi folks! Thank you for your great work on this theme! I was wondering if we could accommodate a few changes to make this repository more accessible and standardized.

1. **Update repository README**: We could sort the list of terminal emulators alphabetically and replace the single line descriptions with a single line like "Click on the link to install the theme for your favorite terminal emulator".
2. **Individual theme standardization**: Within the `src` folder, we could create a folder for each terminal emulator with the theme file, README file and a screenshot of the same application, preferably an alternative of [`neofetch`](https://github.com/dylanaraps/neofetch) like [ `macchina`](https://github.com/Macchina-CLI/macchina) or [`nerdfetch`](https://github.com/thatonecalculator/nerdfetch). Theme files should probably have only the color settings and nothing else, so that they can be easily imported into an existing config.
3. **Add more terminal emulators**: Using [this](https://terminal.sexy) tool we could easily create themes for other popular terminal emulators.
4. **Split into different repositories** (Long-term): Other popular themes, most notably [Dracula](https://github.com/dracula), [Catppuccin](https://github.com/catppuccin) and [Rosé Pine](https://github.com/rose-pine) have separate repositories for each terminal emulator. We could consider adopting the same approach to improve maintainability.

I'd love to contribute towards implementing my first three suggestions, but I'd love to hear your thoughts as well.

**Comment by mngshm** [comment]
Go ahead

**Comment by prateektade** [comment]
Hi @Mangeshrex,

Check out the PR linked above for my work on the various terminal emulator color schemes.

I have also added the Everblush template to two popular terminal color scheme collections - [iTerm2-Color-Schemes](github.com/mbadolato/iTerm2-Color-Schemes/) and [Gogh](https://github.com/Gogh-Co/Gogh).

**Comment by mngshm** [comment]
Cool great work 👍. 

I'll check it out
